// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (queue, payload, status)
VALUES ($1, $2, 'available')
RETURNING id, queue, payload, status
`

type CreateJobParams struct {
	Queue   *int32
	Payload *string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.Queue, arg.Payload)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Queue,
		&i.Payload,
		&i.Status,
	)
	return i, err
}
