// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
